name: free-dict

services:
  db:
    container_name: database
    restart: unless-stopped
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo_data:/data/db

  back:
    container_name: backend
    restart: unless-stopped
    env_file: ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db

  front:
    container_name: frontend
    restart: unless-stopped
    env_file: ./frontend/.env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:5173"

volumes:
  mongo_data: